services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lab3
      - POSTGRES_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    container_name: app
    build:
      context: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    networks:
      - my_network

  celery_task:
    container_name: celery_task
    build:
      context: ./second_task
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    restart: always
    networks:
      - my_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  celery:
    build:
      context: ./second_task
    container_name: celery
    command: celery -A parse worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  db-data:
networks:
  my_network: